### ISSUE TITLE
lib_dir variable empty on Debian 8, 9 and 10

### ISSUE THREAD

**Issue by harmen1994** [sous-chefs/apache2#651]
### :speaking_head: Foreword

When installing the apache2 cookbook via a wrapper the lib_dir variable is not populated.

## :ghost: Brief Description

On Debian based systems the lib_dir variable is not populated, which results in an empty Apache statesdir in /usr/sbin/a2enmod.

## :pancakes: Cookbook version

7.1.1

## :woman_cook:  Chef-Infra Version

14.12 and latest

## :tophat: Platform details

Operating system distribution and release version. Cloud provider if running in the cloud.
Kitchen 1.24.0 and upgraded to 2.2.5
Debian 10 (also reproduced it with 8 and 9), also tested with Centos 7

Following .kitchen.yml
```
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  environments_path: '../../environments'
  data_bags_path: '../../data_bags'
  require_chef_omnibus: "15"
  roles_path: '../../roles'

driver_config:
  network:
    - ["private_network", {ip: "10.0.50.30"}]

verifier:
  name: inspec

platforms:
  - name: debian-10

suites:
  - name: customer-support
    driver:
      customize:
        memory: 2048
        cpus: 8
        audio: "none"
    run_list:
      - role[customer-support]
    attributes:
```

## Steps To Reproduce

1. Put this wrapper recipe in place
```
service 'apache2' do
  extend Apache2::Cookbook::Helpers
  service_name(lazy { apache_platform_service_name })
  supports restart: true, status: true, reload: true
  action :nothing
end

apache2_install 'default' do
  listen [80]
  mpm 'prefork'
  mpm_conf(
    startservers: 16,
    serverlimit: node['apache']['prefork']['serverlimit'],
    maxrequestworkers: node['apache']['prefork']['maxrequestworkers']
  )
  modules lazy { default_modules.delete_if { |x| x == 'autoindex' } }
end
```
2. kitchen create && kitchen converge 
3. In /usr/sbin/a2enmod _/usr/lib/apache2_ was removed on the line of _my $statedir_
4. _my $statedir = $ENV{ uc("APACHE_STATE_DIRECTORY") } || "";_

## :police_car: Expected behavior

The file /usr/sbin/a2enmod should be populated with:
_my $statedir = $ENV{ uc("APACHE_STATE_DIRECTORY") } || "/usr/lib/apache2";_
